markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            A River Called Time
tagline:          'It will wash away everything you hold dear.'
baseurl:          /

author:
  name:           'Wanderer'

paginate:         5

